name: Basic workflow dispatch 

on: 
 workflow_dispatch:
  inputs: 
    environment:
      description: "the environment to deploy"
      required: true
      default: 'production'

jobs:
 deploy:
  runs-on: ubuntu-latest
  steps:
    - run: echo "Deploying to ${{inputs.environment}}"
    
