name: Xray Integration

on:
  workflow_dispatch:
    inputs:
      project-key:
        description: 'Xray project key'
        required: true
        default: 'YAK'
      test-plan-key:
        description: 'Xray test plan key'
        required: true       

jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cypress run
        uses: cypress-io/github-action@v6

      - name: Set environment variables
        env:
          CLIENT_ID: ${{ secrets.XRAY_CLIENT_ID }}  # Replace with your client ID secret
          CLIENT_SECRET: ${{ secrets.XRAY_CLIENT_SECRET }}  # Replace with your client secret secret
        run: |
          echo "CLIENT_ID: $CLIENT_ID"
          echo "CLIENT_SECRET: $CLIENT_SECRET"

      - name: Authenticate with Xray   
        id: authenticate
        run: |
          RESPONSE=$(curl --location --request POST 'https://xray.cloud.getxray.app/api/v1/authenticate' \
          --header 'Content-Type: application/json' \
          --data-raw '{ "client_id": "C2DDC03EB801485E93A8A1BBF29A60F8","client_secret": "f25bc582a1c9a41875413da9a083f5ff082bb241f446780cc705636dbb5feb8c" }')
          echo "Response from Xray: $RESPONSE"
          
      - name: Submit results to Xray
        env:
          XRAY_RESPONSE: $RESPONSE
          run: |
           echo "Response from Xray: $RESPONSE"
        run: |
          echo "Submitting results to Xray..."
          echo "Using Xray authentication response: $XRAY_RESPONSE"
          
          PROJECT_PATH="${{ github.workspace }}"
          FILE_PATH="$PROJECT_PATH/cypress/results/junit/results.xml"
          echo "File Path: $FILE_PATH"
          
          curl -v --location --request POST "https://xray.cloud.getxray.app/api/v1/import/execution/junit?projectKey=${{ github.event.inputs.project-key }}&testPlanKey=${{ github.event.inputs.test-plan-key }}" \
          --header "Authorization: Bearer $XRAY_RESPONSE" \
          --header 'Content-Type: application/xml' \
          --data-binary @"$FILE_PATH"

