name: Xray Integration

on: push

jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cypress run
        uses: cypress-io/github-action@v6

      - name: Submit results to Xray
        env:
          JIRA_SERVER_URL: https://myappyaksha.atlassian.net/
          JIRA_USERNAME: manojnarikdp@gmail.com
          JIRA_API_TOKEN: ATATT3xFfGF0CoWBlEb07p8IwW6CmiIkCAAwP9N1_tzXpBFyk1SK4ADfodj5BOg5GbC58HnEXIwmUxvY0TaGNpNQ7NK4LD9U14fg3S84QzxNb8WFGufmUevYTu09kiSldUTmcC-bteoaLm9AJLvJ3NRW725vYaQpIJrALoC3Ko-IagLNeniw77M=569104D1
          XRAY_CLIENT_ID: 8AC00938E3A0491094CF84962B5D4EA1
          XRAY_CLIENT_SECRET: 2717c2b4c5b82505687417ed9870f9383893293b6026836d589600ef84d8c579
        run: |
          PROJECT_PATH="${{ github.workspace }}"
          FILE_PATH="$PROJECT_PATH/cypress/results/junit/results.xml"
          echo "File Path: $FILE_PATH"
          ls -R $PROJECT_PATH/cypress/results/junit  # Add this line for debugging

          if [ -f "$FILE_PATH" ]; then
            echo "File exists. Submitting results to Xray..."
            RESPONSE=$(curl --location "$JIRA_SERVER_URL/rest/raven/1.0/import/execution/junit?projectKey=YAK&testPlanKey=YAK-4" \
                             --header "Authorization: Basic $JIRA_API_TOKEN" \
                             --header "Content-Type: multipart/form-data" \
                             --form "file=@$FILE_PATH")

            echo "Response: $RESPONSE"

            # Check for errors in the response
            if echo "$RESPONSE" | grep -q '"status-code":404'; then
              echo "Error: 404 - Resource not found."
              exit 1
            fi
          else
            echo "Error: File does not exist at the specified path."
            exit 1
          fi
