name: Xray Integration

# on:
#   workflow_dispatch:
#     inputs:
#       project-key:
#         description: 'Xray project key'
#         required: true
#       test-plan-key:
#         description: 'Xray test plan key'
#         required: true

on: 
 workflow_dispatch:
  inputs: 
    environment:
      description: "the environment to deploy"
      required: true
      default: 'production'

jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cypress run
        uses: cypress-io/github-action@v6

      - name: Authenticate with Xray
        id: authenticate-xray
        env:
          CLIENT_ID: ${{ secrets.CLIENT_ID }}  # Replace with your client ID secret
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}  # Replace with your client secret secret
        run: |
          PROJECT_PATH="${{ github.workspace }}"
          FILE_PATH="$PROJECT_PATH/cypress/results/junit/results.xml"
          echo "File Path: $FILE_PATH"
          
          RESPONSE=$(curl --location --request POST 'https://xray.cloud.getxray.app/api/v1/authenticate' \
          --header 'Content-Type: application/json' \
          --data-raw '{
            "client_id": "'"$CLIENT_ID"'",
            "client_secret": "'"$CLIENT_SECRET"'"
          }')

          XRAY_TOKEN=$(echo "$RESPONSE" | jq -r '.access_token')
          echo "Xray Token: $XRAY_TOKEN"

      - name: Submit results to Xray
        run: |
          PROJECT_PATH="${{ github.workspace }}"
          FILE_PATH="$PROJECT_PATH/cypress/results/juni
