name: Xray Integration

on: 
 workflow_dispatch:
  inputs:
      xray-token:
        description: 'Xray authentication token'
        required: true
      project-key:
        description: 'Xray project key'
        required: true
      test-plan-key:
        description: 'Xray test plan key'
        required: true  

jobs:
  cypress-run:
    runs-on: ubuntu-22.04    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cypress run
        uses: cypress-io/github-action@v6

      - name: Authenticate with Xray
        id: authenticate-xray
        env:
          CLIENT_ID: ${{ secrets.CLIENT_ID }}  # Replace with your client ID secret
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}  # Replace with your client secret secret
        run: |
          PROJECT_PATH="${{ github.workspace }}"
          FILE_PATH="$PROJECT_PATH/cypress/results/junit/results.xml"
          echo "File Path: $FILE_PATH"
          
          RESPONSE=$(curl --location --request POST 'https://xray.cloud.getxray.app/api/v1/authenticate' \
          --header 'Content-Type: application/json' \
          --data-raw '{
            "client_id": "'"$CLIENT_ID"'",
            "client_secret": "'"$CLIENT_SECRET"'"
          }')

          XRAY_TOKEN=$(echo "$RESPONSE" | jq -r '.access_token')
          echo "Xray Token: $XRAY_TOKEN"

      - name: Submit results to Xray
        run: |
          PROJECT_PATH="${{ github.workspace }}"
          FILE_PATH="$PROJECT_PATH/cypress/results/junit/results.xml"
          echo "File Path: $FILE_PATH"
          
          curl --location --request POST "https://xray.cloud.getxray.app/api/v1/import/execution/junit?projectKey=${{ inputs.project-key }}&testPlanKey=${{ inputs.test-plan-key }}" \
          --header "Authorization: Bearer ${{ inputs.xray-token }}" \
          --header 'Content-Type: application/xml' \
          --data-binary "@$FILE_PATH"
