name: Xray Integration

on:
  workflow_dispatch:
    inputs:
      project-key:
        description: 'Xray project key'
        required: true
        default: 'YAK'
      test-plan-key:
        description: 'Xray test plan key'
        required: true       

jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cypress run
        uses: cypress-io/github-action@v6

      - name: Set environment variables
        env:
          CLIENT_ID: ${{ secrets.XRAY_CLIENT_ID }}  # Replace with your client ID secret
          CLIENT_SECRET: ${{ secrets.XRAY_CLIENT_SECRET }}  # Replace with your client secret secret
        run: |
          echo "CLIENT_ID: $CLIENT_ID"
          echo "CLIENT_SECRET: $CLIENT_SECRET"

      - name: Authenticate with Xray     
        run: |
          RESPONSE=$(curl -v --location --request POST 'https://xray.cloud.getxray.app/api/v1/authenticate' \
          --header 'Content-Type: application/json' \
          --data-raw "{\"client_id\": \"$CLIENT_ID\", \"client_secret\": \"$CLIENT_SECRET\"}")
          echo "Response: $RESPONSE"
          XRAY_TOKEN=$(echo "$RESPONSE" | jq -r '.access_token')
          echo "Xray Token: $XRAY_TOKEN"
   
      - name: Submit results to Xray
        env:
          XRAY_TOKEN: ${{ secrets.XRAY_TOKEN }}  # Replace with your Xray token secret
        run: |
          PROJECT_PATH="${{ github.workspace }}"
          FILE_PATH="$PROJECT_PATH/cypress/results/junit/results.xml"
          echo "File Path: $FILE_PATH"
          
          curl --location --request POST "https://xray.cloud.getxray.app/api/v1/import/execution/junit?projectKey=${{ github.event.inputs.project-key }}&testPlanKey=${{ github.event.inputs.test-plan-key }}" \
          --header "Authorization: Bearer $XRAY_TOKEN" \
          --header 'Content-Type: application/xml' \
          --data-binary @"$FILE_PATH"
