name: Xray Integration

on: push

jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cypress run
        uses: cypress-io/github-action@v6

      - name: Submit results to Xray
        env:
          JIRA_SERVER_URL: https://myappyaksha.atlassian.net/
          JIRA_USERNAME: null
          JIRA_API_TOKEN: null
          XRAY_CLIENT_ID: null
          XRAY_CLIENT_SECRET: null
        run: |
          PROJECT_PATH="${{ github.workspace }}"
          FILE_PATH="$PROJECT_PATH/cypress/results/junit/results.xml"
          echo "File Path: $FILE_PATH"
          ls -R $PROJECT_PATH/cypress/results/junit  # Add this line for debugging

          if [ -f "$FILE_PATH" ]; then
            echo "File exists. Submitting results to Xray..."
            RESPONSE=$(curl --location "$JIRA_SERVER_URL/rest/raven/1.0/import/execution/junit?projectKey=YAK&testPlanKey=YAK-4" \
                             --header "Authorization: Basic $JIRA_API_TOKEN" \
                             --header "Content-Type: multipart/form-data" \
                             --form "file=@$FILE_PATH")

            echo "Response: $RESPONSE"

            # Check for errors in the response
            if echo "$RESPONSE" | grep -q '"status-code":404'; then
              echo "Error: 404 - Resource not found."
              exit 1
            fi
          else
            echo "Error: File does not exist at the specified path."
            exit 1
          fi
