name: CI (Jira on-premises example)
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set up Java
        uses: actions/setup-java@v1
        with:
          java-version: "1.8"
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Build with Maven
        run: mvn clean compile test --file pom.xml
      - name: Submit results to Xray
        env:
          JIRA_SERVER_URL: https://myappyaksha.atlassian.net/
          JIRA_USERNAME: manojnarikdp@gmail.com
          JIRA_API_TOKEN: ATATT3xFfGF0CoWBlEb07p8IwW6CmiIkCAAwP9N1_tzXpBFyk1SK4ADfodj5BOg5GbC58HnEXIwmUxvY0TaGNpNQ7NK4LD9U14fg3S84QzxNb8WFGufmUevYTu09kiSldUTmcC-bteoaLm9AJLvJ3NRW725vYaQpIJrALoC3Ko-IagLNeniw77M=569104D1
          XRAY_CLIENT_ID: 8AC00938E3A0491094CF84962B5D4EA1
          XRAY_CLIENT_SECRET: 2717c2b4c5b82505687417ed9870f9383893293b6026836d589600ef84d8c579
        run: 'curl -H "Content-Type: multipart/form-data" -u $JIRA_USERNAME:$JIRA_API_TOKEN -F "file=@target/results/junit/results.xml" "$JIRA_SERVER_URL/rest/raven/1.0/import/execution/junit?projectKey=YAK"'
