name: Xray Upload

on:
  push:
    branches:
      - main

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run PowerShell script
        shell: pwsh
        run: |
          ./.github/workflows/xray_upload.ps1 `
          -client_id "${{ secrets.CLIENT_ID }}" `
          -client_secret "${{ secrets.CLIENT_SECRET }}" `
          -filePath "${{ github.workspace }}/Cypress-xray-integration/githubactionxray/cypress/results/junit/results.xml"
