name: Xray Upload

on:
  push:
    branches:
      - main

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cypress run
        uses: cypress-io/github-action@v6     

      - name: List files in .github/workflows/
        run: |
          ls -al ${{ github.workspace }}/cypress/results/junit/
      
      - name: Merge report
        run: |
          npx junit-merge -d ${{ github.workspace }}/cypress/results/junit/ -o ${{ github.workspace }}/cypress/results/junit/results.xml

      - name: List files in .github/workflows/
        run: |
          ls -al ${{ github.workspace }}/cypress/results/junit/

      - name: Run PowerShell script
        shell: pwsh
        run: |
          ./.github/workflows/xray_upload.ps1 `
          -client_id "C2DDC03EB801485E93A8A1BBF29A60F8" `
          -client_secret "f25bc582a1c9a41875413da9a083f5ff082bb241f446780cc705636dbb5feb8c" `
          -filePath "${{ github.workspace }}/Cypress-xray-integration/githubactionxray/cypress/results/junit/results.xml"
