name: Xray Upload

on:
 workflow_call:
  inputs:
    testid: 
     description: 'Test ID '
     required: true
     type: string
    testexecutionid: 
     description: 'Test Exec ID'
     required: true
     type: string
   
    
  # push:
  #   branches:
  #     - main

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cypress run
        uses: cypress-io/github-action@v6     

      - name: List files in .github/workflows/
        run: |
          ls -al ${{ github.workspace }}/cypress/results/junit/
      
      - name: Merge report
        run: |
          npx junit-merge -d ${{ github.workspace }}/cypress/results/junit/ -o ${{ github.workspace }}/cypress/results/junit/results.xml

      - name: List files in .github/workflows/
        run: |
          ls -al ${{ github.workspace }}/cypress/results/junit/

      - name: Run PowerShell script
        shell: pwsh
        run: |
          ./.github/workflows/xray_upload.ps1 `
          -client_id '${{secrets.XRAY_CLIENT_ID}}' `
          -client_secret '${{secrets.XRAY_CLIENT_SECRET}}' `
          -filePath "${{ github.workspace }}/cypress/results/junit/results.xml" `
          -testId '${{ inputs.testid }}' `
          -testExecId '${{ inputs.testexecutionid }}' `
          
          




