name: Xray Upload
 
on:
  workflow_dispatch:
    inputs:
      testid:
        description: 'Xray testid'
        required: true  
        type: string      
      testexecutionid:
        description: 'Xray execid'
        required: true  
        type: string         

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cypress run
        uses: cypress-io/github-action@v6     

      - name: List files in .github/workflows/
        run: |
          ls -al ${{ github.workspace }}/cypress/results/junit/
      
      - name: Merge report and delete files except results.xml
         run: |
           npx junit-merge -d ${{ github.workspace }}/cypress/results/junit/ -o ${{ github.workspace }}/cypress/results/junit/results.xml
           cd ${{ github.workspace }}/cypress/results/junit/
           ls | grep -v "results.xml" | xargs rm -f


      - name: List files in .github/workflows/
        run: |
          ls -al ${{ github.workspace }}/cypress/results/junit/

     